FROM openjdk:11-jre

WORKDIR app/

ADD ./target/Spring-Boot-Assignment-0.0.1-SNAPSHOT.jar /app/Spring-Boot-Assignment-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app/Spring-Boot-Assignment-0.0.1-SNAPSHOT.jar"]

